### ISSUE TITLE
splitChunks cacheGroup breaks build

### ISSUE THREAD

**Issue by ipmb** [preactjs/preact-cli#1155]
**Do you want to request a _feature_ or report a _bug_?**

Bug (but I'm probably just doing something wrong)

**What is the current behaviour?**

I get the following error with `npm run build`:

```
Unable to read file: /Users/pete/projects/project/src/webpack/bootstrap

TypeError: Cannot read property 'call' of undefined
method: null
at: /Users/pete/projects/project/src/webpack/bootstrap:33:22

Source code:


This could be caused by using DOM or Web APIs.
Pre-render runs in node and has no access to globals available in browsers.

Consider wrapping code producing error in: 'if (typeof window !== "undefined") { ... }'

Alternatively use 'preact build --no-prerender' to disable prerendering.

See https://github.com/developit/preact-cli#pre-rendering for further information.
```

Using `npm run dev`, I get a blank page, no errors in the console.

**If the current behaviour is a bug, please provide the steps to reproduce.**

I see this when I add the following `preact.config.js`:

```javascript
export default {
  webpack(config, env, helpers, options) {
    config.optimization.splitChunks.cacheGroups = {
      aws: {
        chunks: "all",
        enforce: true,
        test: /[\\/]node_modules[\\/]aws/
      }
    };
  }
};
```

**What is the expected behaviour?**

A new bundle is created for modules starting with `aws` and the build works.

**Please mention other relevant information.**

```yaml
Environment Info:
  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    preact: ^10.3.2 => 10.4.1
    preact-cli: ^3.0.0-rc.6 => 3.0.0-rc.10
    preact-render-to-string: ^5.1.4 => 5.1.6
    preact-router: ^3.2.1 => 3.2.1
  npmGlobalPackages:
    preact-cli: 2.2.1
```
